name: Log ISS Location Data Daily

on:
  schedule:
    # Runs at 12:00 UTC (noon) every day
    - cron: "0 12 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:

      - name: Prime cache-3de07b2
        id: prime-cache-3de07b2
        run: echo "Cache hit: ${{ steps.prime-cache-3de07b2.outputs.cache-hit }}"

      - name: Cache Node modules (or other dependencies)
        uses: actions/cache@v4  # Use actions/cache for caching
        with:
          path: node_modules  # Specify the path to cache (for Node.js dependencies)
          key: cache-3de07b2-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}  # Unique cache key
          restore-keys: |
            cache-3de07b2-${{ runner.os }}-
      
      - name: Fetch ISS location data
        run: | # python
          uv run --with requests python << 'EOF'
          import requests

          data = requests.get('http://api.open-notify.org/iss-now.json').text
          with open('iss-location.jsonl', 'a') as f:
              f.write(data + '\n')
          'EOF'

      - name: Commit and push changes
        run: | # shell
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add iss-location.jsonl
          git commit -m "Update ISS position data [skip ci]" || exit 0
          git push