on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f3000795@ds.study.iitm.ac.in
        run: echo "Hello, world !"